version: "3.3"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    networks:
      - common
    ports:
      - ${INFLUXDB_PORT:-8086}:8086
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-influxdb}
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./.docker/influxdb:/var/lib/influxdb

  prometheus:
    image: prom/prometheus:v2.33.1
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    networks:
      - common
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - influxdb
      - prometheus
    depends_on:
      - influxdb
      - prometheus

volumes:
  grafana-storage:

networks:
  common:
    external: true
