version: "3.3"

services:
  couchdb:
    image: couchdb:3.2
    container_name: couchdb
    # user: 1000:1000
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./.docker/couchdb:/opt/couchdb/data
      - ./config/couchdb.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    networks:
      - monitor

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    networks:
      - monitor
    ports:
      - ${INFLUXDB_PORT:-8086}:8086
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-influxdb}
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./.docker/influxdb:/var/lib/influxdb

  prometheus:
    image: prom/prometheus:v2.33.1
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    links:
      - influxdb
      - prometheus
    depends_on:
      - influxdb
      - prometheus
    networks:
      - monitor

volumes:
  grafana-storage:

networks:
  monitor:
    name: monitor
    driver: bridge
