version: "3.3"

services:
  redis:
    image: redis:7.0-alpine
    container_name: yushaku-redis
    ports:
      - 6379:6379
    networks:
      - yu-network

  minio:
    image: bitnami/minio:2022.9.25
    container_name: yushaku-minio
    restart: unless-stopped
    ports:
      - ${MINIO_PORT_ADMIN}:9001
      - ${MINIO_PORT_API}:9000
    environment:
      MINIO_ROOT_USER: ${MINIO_SERVER_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SERVER_SECRET_KEY}
    volumes:
      - ./minio:/data
    networks:
      - yu-network

  nats:
    image: nats:2.9-alpine
    container_name: yushaku-nats
    restart: unless-stopped
    ports:
      - 8222:8222
      - 4222:4222
    networks:
      - yu-network

  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB_MAIN: ${DB_MAIN}
      POSTGRES_DB_TEST: ${DB_TEST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/entrypoint:/docker-entrypoint-initdb.d
    networks:
      - yu-network

networks:
  yu-network:
    driver: bridge
    name: yu-network
