#!/bin/bash

if [ "$1" == "db" ]; then
	docker compose up -d "${@:2-postgres}"

elif [ "$1" == "monitor" ]; then
	docker compose up -d grafana influxdb prometheus

elif [ "$1" == "proxy" ]; then
	docker compose up -d nginx
fi
