global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
